### ISSUE TITLE
模型转换

### ISSUE THREAD

**Issue by cuicui2023** [Tlntin/qwen-ascend-llm#5]
您好，能问一下您做onnx到om模型转换这步用了多久吗？我是Ascend310B1的板子，12G内存，24G交换区，onnx到om模型转换这步好事非常久（好几个小时），然后最后还没成功。
“
[INFO] soc_version is `auto`, will auto detect soc version
[INFO] {'soc_full_name': 'Ascend310B1', 'soc_short_name': 'Ascend310B'}
============ run command ==============
export MS_DEV_FORCE_ACL=1 &&  export MS_ENABLE_GE=1 &&  export TE_PARALLEL_COMPILER=1 && export MAX_COMPILE_CORE_NUMBER=1 && atc --framework=5 --model="./output/onnx2/qwen2_1.5b_chat.onnx" --output="./output/model/qwen2_1.5b_chat" --soc_version=Ascend310B1 --precision_mode_v2=mixed_float16 --modify_mixlist=/home/HwHiAiUser/model/qwen-ascend-llm/ops_info.json --input_format=ND --input_shape="input_ids:1,-1;attention_mask:1,-1;position_ids:1,-1;past_key_values:1,-1,112,128" --dynamic_dims "1,1025,1,1024;2,1026,2,1024;4,1028,4,1024;1,2049,1,2048;2,2050,2,2048;4,2052,4,2048"
=======================================
ATC start working now, please wait for a moment.
Traceback (most recent call last):
  File "/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/te_fusion/fusion_manager.py", line 1912, in set_op_import_module
    importlib.import_module(module_name)
  File "/usr/local/miniconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 786, in exec_module
  File "<frozen importlib._bootstrap_external>", line 922, in get_code
  File "<frozen importlib._bootstrap_external>", line 979, in get_data
PermissionError: [Errno 13] Permission denied: '/usr/local/Ascend/ascend-toolkit/7.0.RC1/opp/vendors/customize/op_impl/ai_core/tbe/customize_impl/mrgba.py'
”
这是怎么回事啊？

**Comment by Tlntin** [comment]
用了多久？回答：10-20分钟。
怎么回事呢？回答：看你的日志：`PermissionError: [Errno 13] Permission denied: '/usr/local/Ascend/ascend-toolkit/7.0.RC1/opp/vendors/customize/op_impl/ai_core/tbe/customize_impl/mrgba.py'`,可能是cann版本较低（看readme推荐的版本），并且建议用root账号操作。
